---
- hosts: aws
  become: yes
  remote_user: ubuntu
  gather_facts: false
  tasks:

   - name: Baixando Sources do Nodejs
     shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

   - name: Inslando o nodejs
     apt:
        name: nodejs
        state: present

   - name: Importando a public key para instalação do MongoDB
     apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

   - name: Create a list file for MongoDB
     shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list

   - name: Atualizando repositório
     apt:
        update_cache: yes

   - name: Instalando pacotes do MongoDB
     apt:
        name: mongodb-org
        state: present

   - name: Verificando o serviço do MongoDB
     service:
        name: mongodb
        state: started
