---
- hosts: aws
  become: yes
  remote_user: ubuntu
  gather_facts: false
  tasks:

   - name: Baixando Sources do Nodejs
     shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -


   - name: Importando a public key para instalação do MongoDB
     apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

   - name: Create a list file for MongoDB
     shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list

   - name: Instalando pacotes
     apt:
        name: "{{ item }}"
        state: present
        update_cache: true
     with_items:
        - nodejs
        - mongodb-org

   - name: Copiando arquivo para configuração do serviço MongoDB
     copy:
      src: ./files/mongodb.service
      dest: /etc/systemd/system/
      force: yes

   - name: Iniciando o serviço recém criado
     systemd: state=started name=mongodb

   - name: Habilitando o serviço do mongo para startup boot
     systemd:
        name: mongodb
        enabled: yes
     notify: reiniciar mongo

  handlers:
     - name: reiniciar mongo
       service:
          name: mongodb
          state: restarted
